apiVersion: v1
kind: Service
metadata:
  name: hello-eks
  labels:
    app: hello-eks
spec:
  # LoadBalancer asks AWS to provision a network load balancer with a
  # public address that routes to the pods. Good for this project but for many
  # real apps you'd use an Ingress controller instead.
  type: LoadBalancer
  selector:
    app: hello-eks
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP